"""Character tables for the 32 crystallographic point groups.

GENERATED FILE - do not edit by hand.
Source: https://symdata.anyterial.se/pointgroup/ (httk-symgen, 0.1.0,
created 2026-09-06T21:45:06.940487Z), license https://creativecommons.org/licenses/by/4.0/.
See httk-sym/ATTRIBUTION.md and scripts/data/generate_character_tables.py.
Generated 2026-10-05T09:10:20 at beyblade 4044803.

One entry per Hermann-Mauguin point-group symbol (spglib spelling),
class-level: characters are listed once per conjugacy class, in the
order of ``classes`` with multiplicities in ``class_sizes``.
"""

# Table of contents: 1, -1, 2, m, 2/m, 222, mm2, mmm, 4, -4, 4/m, 422, 4mm, -42m, 4/mmm, 3, -3, 32, 3m, -3m, 6, -6, 6/m, 622, 6mm, -6m2, 6/mmm, 23, m-3, 432, -43m, m-3m

CLASS_TABLES = {
    "1": {
        "schoenflies": 'C1',
        "order": 1,
        "crystal_system": 'triclinic',
        "laue_class": '-1',
        "is_centrosymmetric": False,
        "classes": ['E'],
        "class_sizes": [1],
        "irreps": {
            "A": {
                "characters": [1.0],
                "dimension": 1,
                "basis_linear": ['x', 'y', 'z'],
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
        },
        "complex_pair": {'A': False},
    },
    "-1": {
        "schoenflies": 'Ci',
        "order": 2,
        "crystal_system": 'triclinic',
        "laue_class": '-1',
        "is_centrosymmetric": True,
        "classes": ['E', 'i'],
        "class_sizes": [1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Au": {
                "characters": [1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['x', 'y', 'z'],
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
        },
        "complex_pair": {'Ag': False, 'Au': False},
    },
    "2": {
        "schoenflies": 'C2',
        "order": 2,
        "crystal_system": 'monoclinic',
        "laue_class": '2/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'C2'],
        "class_sizes": [1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2', 'xz'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "B": {
                "characters": [1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['x', 'z'],
                "basis_rotation": ['Rx', 'Rz'],
                "basis_quadratic": ['xy', 'yz'],
                "label_unicode": 'B',
                "label_latex": 'B',
            },
        },
        "complex_pair": {'A': False, 'B': False},
    },
    "m": {
        "schoenflies": 'Cs',
        "order": 2,
        "crystal_system": 'monoclinic',
        "laue_class": '2/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'sigma_v'],
        "class_sizes": [1, 1],
        "irreps": {
            "A'": {
                "characters": [1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['x', 'z'],
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2', 'xz'],
                "label_unicode": "A'",
                "label_latex": 'A^{\\prime}',
            },
            "A''": {
                "characters": [1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "basis_rotation": ['Rx', 'Rz'],
                "basis_quadratic": ['xy', 'yz'],
                "label_unicode": "A''",
                "label_latex": 'A^{\\prime\\prime}',
            },
        },
        "complex_pair": {"A'": False, "A''": False},
    },
    "2/m": {
        "schoenflies": 'C2h',
        "order": 4,
        "crystal_system": 'monoclinic',
        "laue_class": '2/m',
        "is_centrosymmetric": True,
        "classes": ['E', 'C2', 'i', 'sigma_h'],
        "class_sizes": [1, 1, 1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2', 'xz'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Bg": {
                "characters": [1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rx', 'Rz'],
                "basis_quadratic": ['xy', 'yz'],
                "label_unicode": 'Bg',
                "label_latex": 'B_{g}',
            },
            "Au": {
                "characters": [1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "Bu": {
                "characters": [1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['x', 'z'],
                "label_unicode": 'Bu',
                "label_latex": 'B_{u}',
            },
        },
        "complex_pair": {'Ag': False, 'Bg': False, 'Au': False, 'Bu': False},
    },
    "222": {
        "schoenflies": 'D2',
        "order": 4,
        "crystal_system": 'orthorhombic',
        "laue_class": 'mmm',
        "is_centrosymmetric": False,
        "classes": ['E', 'C2', "C2'", "C2'2"],
        "class_sizes": [1, 1, 1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2', 'y^2', 'z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "B1": {
                "characters": [1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['xz'],
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "B3": {
                "characters": [1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['x'],
                "basis_rotation": ['Rx'],
                "basis_quadratic": ['yz'],
                "label_unicode": 'B₃',
                "label_latex": 'B_{3}',
            },
        },
        "complex_pair": {'A': False, 'B1': False, 'B2': False, 'B3': False},
    },
    "mm2": {
        "schoenflies": 'C2v',
        "order": 4,
        "crystal_system": 'orthorhombic',
        "laue_class": 'mmm',
        "is_centrosymmetric": False,
        "classes": ['E', 'C2', 'sigma_v2', 'sigma_v'],
        "class_sizes": [1, 1, 1, 1],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['x^2', 'y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['xy'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['x'],
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['xz'],
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "basis_rotation": ['Rx'],
                "basis_quadratic": ['yz'],
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False},
    },
    "mmm": {
        "schoenflies": 'D2h',
        "order": 8,
        "crystal_system": 'orthorhombic',
        "laue_class": 'mmm',
        "is_centrosymmetric": True,
        "classes": ['E', 'C2', "C2'", "C2'2", 'i', 'sigma_h', 'sigma_v', 'sigma_v2'],
        "class_sizes": [1, 1, 1, 1, 1, 1, 1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2', 'y^2', 'z^2'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "B1g": {
                "characters": [1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₁g',
                "label_latex": 'B_{1g}',
            },
            "B2g": {
                "characters": [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Ry'],
                "basis_quadratic": ['xz'],
                "label_unicode": 'B₂g',
                "label_latex": 'B_{2g}',
            },
            "B3g": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rx'],
                "basis_quadratic": ['yz'],
                "label_unicode": 'B₃g',
                "label_latex": 'B_{3g}',
            },
            "Au": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "B1u": {
                "characters": [1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'B₁u',
                "label_latex": 'B_{1u}',
            },
            "B2u": {
                "characters": [1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['y'],
                "label_unicode": 'B₂u',
                "label_latex": 'B_{2u}',
            },
            "B3u": {
                "characters": [1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['x'],
                "label_unicode": 'B₃u',
                "label_latex": 'B_{3u}',
            },
        },
        "complex_pair": {'Ag': False, 'B1g': False, 'B2g': False, 'B3g': False, 'Au': False, 'B1u': False, 'B2u': False, 'B3u': False},
    },
    "4": {
        "schoenflies": 'C4',
        "order": 4,
        "crystal_system": 'tetragonal',
        "laue_class": '4/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'C4^3', 'C4', 'C2'],
        "class_sizes": [1, 1, 1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "B": {
                "characters": [1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'B',
                "label_latex": 'B',
            },
            "E": {
                "characters": [2.0, 0.0, 0.0, -2.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A': False, 'B': False, 'E': True},
    },
    "-4": {
        "schoenflies": 'S4',
        "order": 4,
        "crystal_system": 'tetragonal',
        "laue_class": '4/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'C2', 'S4^3', 'S4'],
        "class_sizes": [1, 1, 1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "B": {
                "characters": [1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'B',
                "label_latex": 'B',
            },
            "E": {
                "characters": [2.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A': False, 'B': False, 'E': True},
    },
    "4/m": {
        "schoenflies": 'C4h',
        "order": 8,
        "crystal_system": 'tetragonal',
        "laue_class": '4/m',
        "is_centrosymmetric": True,
        "classes": ['E', 'C4^3', 'C4', 'C2', 'i', 'S4^3', 'S4', 'sigma_h'],
        "class_sizes": [1, 1, 1, 1, 1, 1, 1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Bg": {
                "characters": [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'Bg',
                "label_latex": 'B_{g}',
            },
            "Eg": {
                "characters": [2.0, 0.0, 0.0, -2.0, 2.0, 0.0, 0.0, -2.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "Au": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "Bu": {
                "characters": [1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'Bu',
                "label_latex": 'B_{u}',
            },
            "Eu": {
                "characters": [2.0, 0.0, 0.0, -2.0, -2.0, 0.0, 0.0, 2.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
        },
        "complex_pair": {'Ag': False, 'Bg': False, 'Eg': True, 'Au': False, 'Bu': False, 'Eu': True},
    },
    "422": {
        "schoenflies": 'D4',
        "order": 8,
        "crystal_system": 'tetragonal',
        "laue_class": '4/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', '2C4', 'C2', "2C2'", "2C2''"],
        "class_sizes": [1, 2, 1, 2, 2],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2'],
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "E": {
                "characters": [2.0, 0.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False, 'E': False},
    },
    "4mm": {
        "schoenflies": 'C4v',
        "order": 8,
        "crystal_system": 'tetragonal',
        "laue_class": '4/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', '2C4', 'C2', '2sigma_v', '2sigma_d'],
        "class_sizes": [1, 2, 1, 2, 2],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2'],
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "E": {
                "characters": [2.0, 0.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False, 'E': False},
    },
    "-42m": {
        "schoenflies": 'D2d',
        "order": 8,
        "crystal_system": 'tetragonal',
        "laue_class": '4/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', 'C2', "2C2'", '2S4', '2sigma_d'],
        "class_sizes": [1, 1, 2, 2, 2],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "E": {
                "characters": [2.0, -2.0, 0.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False, 'E': False},
    },
    "4/mmm": {
        "schoenflies": 'D4h',
        "order": 16,
        "crystal_system": 'tetragonal',
        "laue_class": '4/mmm',
        "is_centrosymmetric": True,
        "classes": ['E', '2C4', 'C2', "2C2'", "2C2''", 'i', '2S4', 'sigma_h', '2sigma_v', '2sigma_d'],
        "class_sizes": [1, 2, 1, 2, 2, 1, 2, 1, 2, 2],
        "irreps": {
            "A1g": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁g',
                "label_latex": 'A_{1g}',
            },
            "A2g": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂g',
                "label_latex": 'A_{2g}',
            },
            "B1g": {
                "characters": [1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2-y^2'],
                "label_unicode": 'B₁g',
                "label_latex": 'B_{1g}',
            },
            "B2g": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['xy'],
                "label_unicode": 'B₂g',
                "label_latex": 'B_{2g}',
            },
            "Eg": {
                "characters": [2.0, 0.0, -2.0, 0.0, 0.0, 2.0, 0.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "A1u": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₁u',
                "label_latex": 'A_{1u}',
            },
            "A2u": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'A₂u',
                "label_latex": 'A_{2u}',
            },
            "B1u": {
                "characters": [1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'B₁u',
                "label_latex": 'B_{1u}',
            },
            "B2u": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B₂u',
                "label_latex": 'B_{2u}',
            },
            "Eu": {
                "characters": [2.0, 0.0, -2.0, 0.0, 0.0, -2.0, 0.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
        },
        "complex_pair": {'A1g': False, 'A2g': False, 'B1g': False, 'B2g': False, 'Eg': False, 'A1u': False, 'A2u': False, 'B1u': False, 'B2u': False, 'Eu': False},
    },
    "3": {
        "schoenflies": 'C3',
        "order": 3,
        "crystal_system": 'trigonal',
        "laue_class": '-3',
        "is_centrosymmetric": False,
        "classes": ['E', 'C3^2', 'C3'],
        "class_sizes": [1, 1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "E": {
                "characters": [2.0, -1.0, -1.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['x^2-y^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A': False, 'E': True},
    },
    "-3": {
        "schoenflies": 'S6',
        "order": 6,
        "crystal_system": 'trigonal',
        "laue_class": '-3',
        "is_centrosymmetric": True,
        "classes": ['E', 'C3^2', 'C3', 'i', 'S6^5', 'S6'],
        "class_sizes": [1, 1, 1, 1, 1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Eg": {
                "characters": [2.0, -1.0, -1.0, 2.0, -1.0, -1.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['x^2-y^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "Au": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "Eu": {
                "characters": [2.0, -1.0, -1.0, -2.0, 1.0, 1.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
        },
        "complex_pair": {'Ag': False, 'Eg': True, 'Au': False, 'Eu': True},
    },
    "32": {
        "schoenflies": 'D3',
        "order": 6,
        "crystal_system": 'trigonal',
        "laue_class": '-3m',
        "is_centrosymmetric": False,
        "classes": ['E', '2C3', "3C2''"],
        "class_sizes": [1, 2, 3],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "E": {
                "characters": [2.0, -1.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['x^2-y^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'E': False},
    },
    "3m": {
        "schoenflies": 'C3v',
        "order": 6,
        "crystal_system": 'trigonal',
        "laue_class": '-3m',
        "is_centrosymmetric": False,
        "classes": ['E', '2C3', '3sigma_v'],
        "class_sizes": [1, 2, 3],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "E": {
                "characters": [2.0, -1.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['x^2-y^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'E': False},
    },
    "-3m": {
        "schoenflies": 'D3d',
        "order": 12,
        "crystal_system": 'trigonal',
        "laue_class": '-3m',
        "is_centrosymmetric": True,
        "classes": ['E', '2C3', "3C2''", 'i', '2S6', '3sigma_d'],
        "class_sizes": [1, 2, 3, 1, 2, 3],
        "irreps": {
            "A1g": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁g',
                "label_latex": 'A_{1g}',
            },
            "A2g": {
                "characters": [1.0, 1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂g',
                "label_latex": 'A_{2g}',
            },
            "Eg": {
                "characters": [2.0, -1.0, 0.0, 2.0, -1.0, 0.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['x^2-y^2', 'xy', 'xz', 'yz'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "A1u": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₁u',
                "label_latex": 'A_{1u}',
            },
            "A2u": {
                "characters": [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'A₂u',
                "label_latex": 'A_{2u}',
            },
            "Eu": {
                "characters": [2.0, -1.0, 0.0, -2.0, 1.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
        },
        "complex_pair": {'A1g': False, 'A2g': False, 'Eg': False, 'A1u': False, 'A2u': False, 'Eu': False},
    },
    "6": {
        "schoenflies": 'C6',
        "order": 6,
        "crystal_system": 'hexagonal',
        "laue_class": '6/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'C6^5', 'C6', 'C3^2', 'C3', 'C2'],
        "class_sizes": [1, 1, 1, 1, 1, 1],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "B": {
                "characters": [1.0, -1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B',
                "label_latex": 'B',
            },
            "E1": {
                "characters": [2.0, 1.0, 1.0, -1.0, -1.0, -2.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E₁',
                "label_latex": 'E_{1}',
            },
            "E2": {
                "characters": [2.0, -1.0, -1.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'E₂',
                "label_latex": 'E_{2}',
            },
        },
        "complex_pair": {'A': False, 'B': False, 'E1': True, 'E2': True},
    },
    "-6": {
        "schoenflies": 'C3h',
        "order": 6,
        "crystal_system": 'hexagonal',
        "laue_class": '6/m',
        "is_centrosymmetric": False,
        "classes": ['E', 'C3^2', 'C3', 'S3^5', 'S3', 'sigma_h'],
        "class_sizes": [1, 1, 1, 1, 1, 1],
        "irreps": {
            "A'": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": "A'",
                "label_latex": 'A^{\\prime}',
            },
            "E'": {
                "characters": [2.0, -1.0, -1.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": "E'",
                "label_latex": 'E^{\\prime}',
            },
            "A''": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": "A''",
                "label_latex": 'A^{\\prime\\prime}',
            },
            "E''": {
                "characters": [2.0, -1.0, -1.0, 1.0, 1.0, -2.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": "E''",
                "label_latex": 'E^{\\prime\\prime}',
            },
        },
        "complex_pair": {"A'": False, "E'": True, "A''": False, "E''": True},
    },
    "6/m": {
        "schoenflies": 'C6h',
        "order": 12,
        "crystal_system": 'hexagonal',
        "laue_class": '6/m',
        "is_centrosymmetric": True,
        "classes": ['E', 'C6^5', 'C6', 'C3^2', 'C3', 'C2', 'i', 'S6^5', 'S6', 'S3^5', 'S3', 'sigma_h'],
        "class_sizes": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Bg": {
                "characters": [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'Bg',
                "label_latex": 'B_{g}',
            },
            "E1g": {
                "characters": [2.0, 1.0, 1.0, -1.0, -1.0, -2.0, 2.0, -1.0, -1.0, 1.0, 1.0, -2.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E₁g',
                "label_latex": 'E_{1g}',
            },
            "E2g": {
                "characters": [2.0, -1.0, -1.0, -1.0, -1.0, 2.0, 2.0, -1.0, -1.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'E₂g',
                "label_latex": 'E_{2g}',
            },
            "Au": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "Bu": {
                "characters": [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'Bu',
                "label_latex": 'B_{u}',
            },
            "E1u": {
                "characters": [2.0, 1.0, 1.0, -1.0, -1.0, -2.0, -2.0, 1.0, 1.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'E₁u',
                "label_latex": 'E_{1u}',
            },
            "E2u": {
                "characters": [2.0, -1.0, -1.0, -1.0, -1.0, 2.0, -2.0, 1.0, 1.0, 1.0, 1.0, -2.0],
                "dimension": 2,
                "label_unicode": 'E₂u',
                "label_latex": 'E_{2u}',
            },
        },
        "complex_pair": {'Ag': False, 'Bg': False, 'E1g': True, 'E2g': True, 'Au': False, 'Bu': False, 'E1u': True, 'E2u': True},
    },
    "622": {
        "schoenflies": 'D6',
        "order": 12,
        "crystal_system": 'hexagonal',
        "laue_class": '6/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', '2C6', '2C3', 'C2', "3C2'", "3C2''"],
        "class_sizes": [1, 2, 2, 1, 3, 3],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "E1": {
                "characters": [2.0, 1.0, -1.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E₁',
                "label_latex": 'E_{1}',
            },
            "E2": {
                "characters": [2.0, -1.0, -1.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'E₂',
                "label_latex": 'E_{2}',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False, 'E1': False, 'E2': False},
    },
    "6mm": {
        "schoenflies": 'C6v',
        "order": 12,
        "crystal_system": 'hexagonal',
        "laue_class": '6/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', '2C6', '2C3', 'C2', '3sigma_v', '3sigma_d'],
        "class_sizes": [1, 2, 2, 1, 3, 3],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "B1": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B₁',
                "label_latex": 'B_{1}',
            },
            "B2": {
                "characters": [1.0, -1.0, 1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'B₂',
                "label_latex": 'B_{2}',
            },
            "E1": {
                "characters": [2.0, 1.0, -1.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E₁',
                "label_latex": 'E_{1}',
            },
            "E2": {
                "characters": [2.0, -1.0, -1.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'E₂',
                "label_latex": 'E_{2}',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'B1': False, 'B2': False, 'E1': False, 'E2': False},
    },
    "-6m2": {
        "schoenflies": 'D3h',
        "order": 12,
        "crystal_system": 'hexagonal',
        "laue_class": '6/mmm',
        "is_centrosymmetric": False,
        "classes": ['E', '2C3', "3C2''", 'sigma_h', '2S3', '3sigma_v'],
        "class_sizes": [1, 2, 3, 1, 2, 3],
        "irreps": {
            "A1'": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": "A₁'",
                "label_latex": 'A_{1}^{\\prime}',
            },
            "A2'": {
                "characters": [1.0, 1.0, -1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": "A₂'",
                "label_latex": 'A_{2}^{\\prime}',
            },
            "E'": {
                "characters": [2.0, -1.0, 0.0, 2.0, -1.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": "E'",
                "label_latex": 'E^{\\prime}',
            },
            "A2''": {
                "characters": [1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": "A₁''",
                "label_latex": 'A_{1}^{\\prime\\prime}',
            },
            "A1''": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": "A₂''",
                "label_latex": 'A_{2}^{\\prime\\prime}',
            },
            "E''": {
                "characters": [2.0, -1.0, 0.0, -2.0, 1.0, 0.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": "E''",
                "label_latex": 'E^{\\prime\\prime}',
            },
        },
        "complex_pair": {"A1'": False, "A2'": False, "E'": False, "A2''": False, "A1''": False, "E''": False},
    },
    "6/mmm": {
        "schoenflies": 'D6h',
        "order": 24,
        "crystal_system": 'hexagonal',
        "laue_class": '6/mmm',
        "is_centrosymmetric": True,
        "classes": ['E', '2C6', '2C3', 'C2', "3C2'", "3C2''", 'i', '2S6', '2S3', 'sigma_h', '3sigma_v', '3sigma_d'],
        "class_sizes": [1, 2, 2, 1, 3, 3, 1, 2, 2, 1, 3, 3],
        "irreps": {
            "A1g": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2', 'z^2'],
                "label_unicode": 'A₁g',
                "label_latex": 'A_{1g}',
            },
            "A2g": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "basis_rotation": ['Rz'],
                "label_unicode": 'A₂g',
                "label_latex": 'A_{2g}',
            },
            "B1g": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B₁g',
                "label_latex": 'B_{1g}',
            },
            "B2g": {
                "characters": [1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'B₂g',
                "label_latex": 'B_{2g}',
            },
            "E1g": {
                "characters": [2.0, 1.0, -1.0, -2.0, 0.0, 0.0, 2.0, -1.0, 1.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_rotation": ['Rx', 'Ry'],
                "basis_quadratic": ['xz', 'yz'],
                "label_unicode": 'E₁g',
                "label_latex": 'E_{1g}',
            },
            "E2g": {
                "characters": [2.0, -1.0, -1.0, 2.0, 0.0, 0.0, 2.0, -1.0, -1.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-y^2', 'xy'],
                "label_unicode": 'E₂g',
                "label_latex": 'E_{2g}',
            },
            "A1u": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₁u',
                "label_latex": 'A_{1u}',
            },
            "A2u": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_linear": ['z'],
                "label_unicode": 'A₂u',
                "label_latex": 'A_{2u}',
            },
            "B1u": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'B₁u',
                "label_latex": 'B_{1u}',
            },
            "B2u": {
                "characters": [1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'B₂u',
                "label_latex": 'B_{2u}',
            },
            "E1u": {
                "characters": [2.0, 1.0, -1.0, -2.0, 0.0, 0.0, -2.0, 1.0, -1.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_linear": ['x', 'y'],
                "label_unicode": 'E₁u',
                "label_latex": 'E_{1u}',
            },
            "E2u": {
                "characters": [2.0, -1.0, -1.0, 2.0, 0.0, 0.0, -2.0, 1.0, 1.0, -2.0, 0.0, 0.0],
                "dimension": 2,
                "label_unicode": 'E₂u',
                "label_latex": 'E_{2u}',
            },
        },
        "complex_pair": {'A1g': False, 'A2g': False, 'B1g': False, 'B2g': False, 'E1g': False, 'E2g': False, 'A1u': False, 'A2u': False, 'B1u': False, 'B2u': False, 'E1u': False, 'E2u': False},
    },
    "23": {
        "schoenflies": 'T',
        "order": 12,
        "crystal_system": 'cubic',
        "laue_class": 'm-3',
        "is_centrosymmetric": False,
        "classes": ['E', '4C3', '4C32', '3C2'],
        "class_sizes": [1, 4, 4, 3],
        "irreps": {
            "A": {
                "characters": [1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2+z^2'],
                "label_unicode": 'A',
                "label_latex": 'A',
            },
            "E": {
                "characters": [2.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-1/2*y^2-1/2*z^2', 'x^2-2*y^2+z^2'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
            "T": {
                "characters": [3.0, 0.0, 0.0, -1.0],
                "dimension": 3,
                "basis_linear": ['x', 'y', 'z'],
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "basis_quadratic": ['xy', 'xz', 'yz'],
                "label_unicode": 'T',
                "label_latex": 'T',
            },
        },
        "complex_pair": {'A': False, 'E': True, 'T': False},
    },
    "m-3": {
        "schoenflies": 'Th',
        "order": 24,
        "crystal_system": 'cubic',
        "laue_class": 'm-3',
        "is_centrosymmetric": True,
        "classes": ['E', '4C3', '4C32', '3C2', 'i', '4S6', '4S62', '3sigma_v'],
        "class_sizes": [1, 4, 4, 3, 1, 4, 4, 3],
        "irreps": {
            "Ag": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2+z^2'],
                "label_unicode": 'Ag',
                "label_latex": 'A_{g}',
            },
            "Eg": {
                "characters": [2.0, -1.0, -1.0, 2.0, 2.0, -1.0, -1.0, 2.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-1/2*y^2-1/2*z^2', 'x^2-2*y^2+z^2'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "Tg": {
                "characters": [3.0, 0.0, 0.0, -1.0, 3.0, 0.0, 0.0, -1.0],
                "dimension": 3,
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "basis_quadratic": ['xy', 'xz', 'yz'],
                "label_unicode": 'Tg',
                "label_latex": 'T_{g}',
            },
            "Au": {
                "characters": [1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'Au',
                "label_latex": 'A_{u}',
            },
            "Eu": {
                "characters": [2.0, -1.0, -1.0, 2.0, -2.0, 1.0, 1.0, -2.0],
                "dimension": 2,
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
            "Tu": {
                "characters": [3.0, 0.0, 0.0, -1.0, -3.0, 0.0, 0.0, 1.0],
                "dimension": 3,
                "basis_linear": ['x', 'y', 'z'],
                "label_unicode": 'Tu',
                "label_latex": 'T_{u}',
            },
        },
        "complex_pair": {'Ag': False, 'Eg': True, 'Tg': False, 'Au': False, 'Eu': True, 'Tu': False},
    },
    "432": {
        "schoenflies": 'O',
        "order": 24,
        "crystal_system": 'cubic',
        "laue_class": 'm-3m',
        "is_centrosymmetric": False,
        "classes": ['E', '6C4', '8C3', '6C2', "3C2'"],
        "class_sizes": [1, 6, 8, 6, 3],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2+z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "E": {
                "characters": [2.0, 0.0, -1.0, 0.0, 2.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-1/2*y^2-1/2*z^2', 'x^2-2*y^2+z^2'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
            "T1": {
                "characters": [3.0, 1.0, 0.0, -1.0, -1.0],
                "dimension": 3,
                "basis_linear": ['x', 'y', 'z'],
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "label_unicode": 'T₁',
                "label_latex": 'T_{1}',
            },
            "T2": {
                "characters": [3.0, -1.0, 0.0, 1.0, -1.0],
                "dimension": 3,
                "basis_quadratic": ['xy', 'xz', 'yz'],
                "label_unicode": 'T₂',
                "label_latex": 'T_{2}',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'E': False, 'T1': False, 'T2': False},
    },
    "-43m": {
        "schoenflies": 'Td',
        "order": 24,
        "crystal_system": 'cubic',
        "laue_class": 'm-3m',
        "is_centrosymmetric": False,
        "classes": ['E', '8C3', '3C2', '6S4', '6sigma_d'],
        "class_sizes": [1, 8, 3, 6, 6],
        "irreps": {
            "A1": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2+z^2'],
                "label_unicode": 'A₁',
                "label_latex": 'A_{1}',
            },
            "A2": {
                "characters": [1.0, 1.0, 1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₂',
                "label_latex": 'A_{2}',
            },
            "E": {
                "characters": [2.0, -1.0, 2.0, 0.0, 0.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-1/2*y^2-1/2*z^2', 'x^2-2*y^2+z^2'],
                "label_unicode": 'E',
                "label_latex": 'E',
            },
            "T1": {
                "characters": [3.0, 0.0, -1.0, 1.0, -1.0],
                "dimension": 3,
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "label_unicode": 'T₁',
                "label_latex": 'T_{1}',
            },
            "T2": {
                "characters": [3.0, 0.0, -1.0, -1.0, 1.0],
                "dimension": 3,
                "basis_linear": ['x', 'y', 'z'],
                "basis_quadratic": ['xy', 'xz', 'yz'],
                "label_unicode": 'T₂',
                "label_latex": 'T_{2}',
            },
        },
        "complex_pair": {'A1': False, 'A2': False, 'E': False, 'T1': False, 'T2': False},
    },
    "m-3m": {
        "schoenflies": 'Oh',
        "order": 48,
        "crystal_system": 'cubic',
        "laue_class": 'm-3m',
        "is_centrosymmetric": True,
        "classes": ['E', '6C4', '8C3', '6C2', "3C2'", 'i', '8S6', '6S4', '3sigma_v', '6sigma_d'],
        "class_sizes": [1, 6, 8, 6, 3, 1, 8, 6, 3, 6],
        "irreps": {
            "A1g": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                "dimension": 1,
                "basis_quadratic": ['x^2+y^2+z^2'],
                "label_unicode": 'A₁g',
                "label_latex": 'A_{1g}',
            },
            "A2g": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₂g',
                "label_latex": 'A_{2g}',
            },
            "Eg": {
                "characters": [2.0, 0.0, -1.0, 0.0, 2.0, 2.0, -1.0, 0.0, 2.0, 0.0],
                "dimension": 2,
                "basis_quadratic": ['x^2-1/2*y^2-1/2*z^2', 'x^2-2*y^2+z^2'],
                "label_unicode": 'Eg',
                "label_latex": 'E_{g}',
            },
            "T1g": {
                "characters": [3.0, 1.0, 0.0, -1.0, -1.0, 3.0, 0.0, 1.0, -1.0, -1.0],
                "dimension": 3,
                "basis_rotation": ['Rx', 'Ry', 'Rz'],
                "label_unicode": 'T₁g',
                "label_latex": 'T_{1g}',
            },
            "T2g": {
                "characters": [3.0, -1.0, 0.0, 1.0, -1.0, 3.0, 0.0, -1.0, -1.0, 1.0],
                "dimension": 3,
                "basis_quadratic": ['xy', 'xz', 'yz'],
                "label_unicode": 'T₂g',
                "label_latex": 'T_{2g}',
            },
            "A1u": {
                "characters": [1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
                "dimension": 1,
                "label_unicode": 'A₁u',
                "label_latex": 'A_{1u}',
            },
            "A2u": {
                "characters": [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0],
                "dimension": 1,
                "label_unicode": 'A₂u',
                "label_latex": 'A_{2u}',
            },
            "Eu": {
                "characters": [2.0, 0.0, -1.0, 0.0, 2.0, -2.0, 1.0, 0.0, -2.0, 0.0],
                "dimension": 2,
                "label_unicode": 'Eu',
                "label_latex": 'E_{u}',
            },
            "T1u": {
                "characters": [3.0, 1.0, 0.0, -1.0, -1.0, -3.0, 0.0, -1.0, 1.0, 1.0],
                "dimension": 3,
                "basis_linear": ['x', 'y', 'z'],
                "label_unicode": 'T₁u',
                "label_latex": 'T_{1u}',
            },
            "T2u": {
                "characters": [3.0, -1.0, 0.0, 1.0, -1.0, -3.0, 0.0, 1.0, 1.0, -1.0],
                "dimension": 3,
                "label_unicode": 'T₂u',
                "label_latex": 'T_{2u}',
            },
        },
        "complex_pair": {'A1g': False, 'A2g': False, 'Eg': False, 'T1g': False, 'T2g': False, 'A1u': False, 'A2u': False, 'Eu': False, 'T1u': False, 'T2u': False},
    },
}
