[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "beyblade"
version = "2026.09.01"
license = "GPL-3.0-or-later"
requires-python = ">= 3.10"
dependencies = [
    "numpy",
    "scipy",
    "pymatgen",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]
